#!/bin/bash

# Script to plot the local magnetic moment of the system, using mulliken population. It uses the bash script calc_pop that can be found here: https://github.com/caiovincius/SIESTA-Shell-Tools.

PATH_scripts="/home/vigir2/Stage E23/Utils"

if [ -z $1 ]
then
	echo You must put the system label in argument. Ex: plot_mulliken [SystemLabel]
	exit
fi
if ! [ -e $1.out ]
then 
	echo $1.out was not found in the directory. Try again.
	exit
fi
if ! [ -e $1.xyz ]
then 
	echo $1.xyz was not found in the directory. Try again.
	exit
fi

sys_label=$1

calc_pop ${sys_label}.out 

python "$PATH_scripts"/read_mulliken.py $sys_label

rm arquivo*

python "$PATH_scripts"/plot_mulliken.py $sys_label

echo End

